# Generated by Django 3.2.6 on 2021-08-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Codefury_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APP',
        ),
    ]
