# Generated by Django 3.2.6 on 2021-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codefury_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
