# Generated by Django 3.2.6 on 2021-08-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codefury_app', '0004_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=100)),
                ('answer', models.TextField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='announcment',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcment',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
