# Generated by Django 3.2.6 on 2021-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codefury_app', '0005_auto_20210826_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcment',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
