# Generated by Django 3.2.6 on 2021-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codefury_app', '0008_auto_20210901_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcment',
            name='title',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
